apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::452251620858:role/EKSClusterS3WriterIAMRole
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"eks-s3-access","namespace":"default"}}
  name: eks-s3-access
  namespace: default
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "* * * * *"  # Run every minute (cron syntax)
  concurrencyPolicy: Forbid  # Optional: Prevent concurrent executions (default: Allow)
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: eks-s3-access
          containers:
            - name: my-container
              image: python:slim
              #command: ["python", "/code/cronjob.py"]
              command: ["/bin/sh","-c"]
              args: ["pip install requests boto3; printenv; python /code/cronjob.py"]
              volumeMounts:
                - name: python-script
                  mountPath: /code
          volumes:
            - name: python-script
              configMap:
                name: python-script
          restartPolicy: OnFailure  # Optional: Restart policy for the container
